### PR TITLE
Python 3 compatible import of pickle

### PR DESCRIPTION
**Pull request by cclauss**
As requested by @Phuket2

https://forum.omz-software.com/topic/3494/navview-template/3

### CODE REVIEW

**Comment by ncarding** [comment]
Thanks @cclauss. I was just looking into that. Is there any particular reason you have rearranged the order of the import statements?

Do you think it's necessary to alter the protocol as @Phuket2 suggested? I was thinking not, assuming if you run the code in Python 3 you would not need to then run it in Python 2 (once the pickle files have been created).

**Comment by Phuket2** [comment]
@ncarding , regarding the protocol, to me it would seem smart to keep it compatible between py2.7 and 3.5x , I could not imagine there would be a significant difference in speed with a hand made dataset like this.  Meaning, the highest protocol is not really needed or is least significant when weighting up compatibility vrs speed.  Its a trade off, I guess.  But I suspect all the pickle calls will be lighting fast with such a small dataset.

**Comment by cclauss** [comment]
``` python
import pickle
print(pickle.HIGHEST_PROTOCOL)  # 2 on Python 2 and 4 on Python 3.5
```

If you think people are going to be emailing these files to each other then set protocol to 2 when writing files.

**Comment by ncarding** [comment]
I just tried changing the protocol to 2 but I still got an "NEWOBJ class argument isn't a type object" unpicking error from my open_file function when I went from Python 3.5 back to 2.7.

I don't expect people to email the files or to be jumping between versions of Python, but I thought it might be useful when developing/testing this template if I want to keep it compatible with both versions of Python.

**Comment by cclauss** [comment]
Please make sure that you are only setting the protocol on write and NOT on read.  Let the read (pickle.load()) read the file in whatever format it thinks is best but force it to use protocol of 2 on write (pickle.dump()).

**Comment by ncarding** [comment]
I've just double checked and I am only setting the protocol on write. Could it be something to do with the way I'm reading the file?

``` python
def open_file(self, filename):
        """
        Opens Pickle file and extracts all the objects into a list
        """
        if os.path.isfile(filename):
            with open(filename, "rb") as input:
                while True:
                    try:
                        yield pickle.load(input)
                    except EOFError:
                        break
```

**Comment by cclauss** [comment]
I would change the name of this method from `open_file()`to `read_file()`to more accurately reflect all that it does.  Yield is only useful when you will yield more than once like if you were going to read a file chunk by chunk.  In this case however `pickle.load()`will read the entire file in a single operation.  I would therefore rewrite it as:

``` python
def read_file(self, filename):
    """
    Opens Pickle file and extracts all the objects into a list
    """
    try:
         with open(filename, "rb") as in_file:
                return pickle.load(in_file)
    except FileNotFoundError:
        print(filename, 'not found.')
```

**Comment by ncarding** [comment]
I've just tried that and it looks like FileNotFoundError is not part of Python 2.7. So I tried IOError which seemed to work but then it through up a new error.

This was all a nice to have and not my priority at the moment, so I think for now I will put up with the fact that you can't jump back and forth between Python versions with the same pickle files. I have however changed the function name. Thanks for your help.

**Pull request merged**
